export const OPERATION_BEGIN = 'OPERATION_BEGIN';

export const SHOW_ALERT = 'SHOW_ALERT';
export const CLEAR_ALERT = 'CLEAR_ALERT';

export const VERIFY_AUTH_SUCCESS = 'VERIFY_AUTH_SUCCESS';
export const VERIFY_AUTH_ERROR = 'VERIFY_AUTH_ERROR';

export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR';

export const LOGOUT_USER_SUCCESS = 'LOGOUT_USER_SUCCESS';
export const LOGOUT_USER_ERROR = 'LOGOUT_USER_ERROR';

export const REGISTER_CUSTOMER_SUCCESS = 'REGISTER_CUSTOMER_SUCCESS';
export const REGISTER_CUSTOMER_ERROR = 'REGISTER_CUSTOMER_ERROR';

export const CREATE_CUSTOMER_SUCCESS = 'CREATE_CUSTOMER_SUCCESS';
export const CREATE_CUSTOMER_ERROR = 'CREATE_CUSTOMER_ERROR';

export const GET_CUSTOMERS_SUCCESS = 'GET_CUSTOMERS_SUCCESS';
export const GET_CUSTOMERS_ERROR = 'GET_CUSTOMERS_ERROR';

export const GET_MODALITIES_SUCCESS = 'GET_MODALITIES_SUCCESS';
export const GET_MODALITIES_ERROR = 'GET_MODALITIES_ERROR';

export const ADD_NEW_MODALITY_SUCCESS = 'ADD_NEW_MODALITY_SUCCESS';
export const ADD_NEW_MODALITY_ERROR = 'ADD_NEW_MODALITY_ERROR';

export const UPDATE_MODALITY_SUCCESS = 'UPDATE_MODALITY_SUCCESS';
export const UPDATE_MODALITY_ERROR = 'UPDATE_MODALITY_SUCCESS';

export const DELETE_MODALITY_SUCCESS = 'DELETE_MODALITY_SUCCESS';
export const DELETE_MODALITY_ERROR = 'DELETE_MODALITY_ERROR';
