class Actions {
  OPERATION_BEGIN = 'OPERATION_BEGIN';

  SHOW_ALERT = 'SHOW_ALERT';
  CLEAR_ALERT = 'CLEAR_ALERT';

  //
  // Auth
  //

  VERIFY_AUTH_SUCCESS = 'VERIFY_AUTH_SUCCESS';
  VERIFY_AUTH_ERROR = 'VERIFY_AUTH_ERROR';

  LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
  LOGIN_USER_ERROR = 'LOGIN_USER_ERROR';

  LOGOUT_USER_SUCCESS = 'LOGOUT_USER_SUCCESS';
  LOGOUT_USER_ERROR = 'LOGOUT_USER_ERROR';

  //
  // Consumers
  //

  REGISTER_CUSTOMER_SUCCESS = 'REGISTER_CUSTOMER_SUCCESS';
  REGISTER_CUSTOMER_ERROR = 'REGISTER_CUSTOMER_ERROR';

  GET_CUSTOMERS_SUCCESS = 'GET_CUSTOMERS_SUCCESS';
  GET_CUSTOMERS_ERROR = 'GET_CUSTOMERS_ERROR';

  //
  // Modalities
  //

  GET_MODALITIES_SUCCESS = 'GET_MODALITIES_SUCCESS';
  GET_MODALITIES_ERROR = 'GET_MODALITIES_ERROR';

  ADD_NEW_MODALITY_SUCCESS = 'ADD_NEW_MODALITY_SUCCESS';
  ADD_NEW_MODALITY_ERROR = 'ADD_NEW_MODALITY_ERROR';

  UPDATE_MODALITY_SUCCESS = 'UPDATE_MODALITY_SUCCESS';
  UPDATE_MODALITY_ERROR = 'UPDATE_MODALITY_SUCCESS';

  DELETE_MODALITY_SUCCESS = 'DELETE_MODALITY_SUCCESS';
  DELETE_MODALITY_ERROR = 'DELETE_MODALITY_ERROR';

  //
  // Plans
  //

  GET_PLANS_SUCCESS = 'GET_PLANS_SUCCESS';
  GET_PLANS_ERROR = 'GET_PLANS_ERROR';

  ADD_NEW_PLAN_SUCCESS = 'ADD_NEW_PLAN_SUCCESS';
  ADD_NEW_PLAN_ERROR = 'ADD_NEW_PLAN_ERROR';

  UPDATE_PLAN_SUCCESS = 'UPDATE_PLAN_SUCCESS';
  UPDATE_PLAN_ERROR = 'UPDATE_PLAN_SUCCESS';

  DELETE_PLAN_SUCCESS = 'DELETE_PLAN_SUCCESS';
  DELETE_PLAN_ERROR = 'DELETE_PLAN_ERROR';

  //
  // USER
  //

  GET_USER_SUCCESS = 'GET_USER_SUCCESS';
  GET_USER_ERROR = 'GET_USER_ERROR';
  UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
  UPDATE_USER_ERROR = 'UPDATE_USER_ERROR';

  //
  // MEMBERSHIPS
  //

  GET_CUSTOMER_MEMBERSHIPS_SUCCESS = 'GET_CUSTOMER_MEMBERSHIPS_SUCCESS';
  GET_CUSTOMER_MEMBERSHIPS_ERROR = 'GET_CUSTOMER_MEMBERSHIPS_ERROR';

  CREATE_CUSTOMER_MEMBERSHIP_SUCCESS = 'CREATE_CUSTOMER_MEMBERSHIP_SUCCESS';
  CREATE_CUSTOMER_MEMBERSHIP_ERROR = 'CREATE_CUSTOMER_MEMBERSHIP_ERROR';

  //
  // CLASS GROUPS
  //

  GET_CLASS_GROUPS_SUCCESS = 'GET_CLASS_GROUPS_SUCCESS';
  GET_CLASS_GROUPS_ERROR = 'GET_CLASS_GROUPS_ERROR';

  CREATE_CLASS_GROUP_SUCCESS = 'CREATE_CLASS_GROUP_SUCCESS';
  CREATE_CLASS_GROUP_ERROR = 'CREATE_CLASS_GROUP_ERROR';
}

const actions = new Actions();

export default actions;
